handler:
  host : localhost
  port : 9082
storage-handler:
  host : localhost
  port : 9083
clerk: 
  host : localhost
  port : 9086
uploader:
  host: localhost
  port: 8085
s3-temp-storage:
  key: 009145048a6e9c39de76
  bucket: zhbluzern-test
  api-url-value: https://s3-zh.lts.switch.ch
  url: s3-zh.lts.switch.ch
  upload-folder: vfs:/temp_switch_ch

#modify if needed the hosts/ports